version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.09.0-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Run Container
          command: |
            alias aws='docker run --rm -t $(tty &>/dev/null && echo "-i") -v "$(pwd):/project" -v "${HOME}/.aws:/root/.aws" app' 
            if ![ aws --version | grep "${CIRCLE_TAG}" ]; then
              exit 1
            fi
      - run:
          name: Push Docker image
          command: |
              docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
              docker tag app "nmemoto/aws-cli:${CIRCLE_TAG}"
              docker push "nmemoto/aws-cli:${CIRCLE_TAG}"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9.]+$/
