version: 2
jobs:
  check:
    working_directory: ~/workspace
    docker:
      - image: docker:18.09.3-git
    environment:
      AWSCLI_LATEST_VERSION: 1.16.202
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check Version
          command: |
            latest_version=$(docker run --rm nmemoto/grlr aws/aws-cli)
            if [ "$AWSCLI_LATEST_VERSION" != "$latest_version" ]; then  
              sed -i -e "s/AWSCLI_LATEST_VERSION: [0-9.][0-9.]*$/AWSCLI_LATEST_VERSION: $latest_version/" .circleci/config.yml
              sed -i -e "s/^ENV AWS_CLI_VERSION \"[0-9.][0-9.]*\"$/ENV AWS_CLI_VERSION \"$latest_version\"/" Dockerfile
              sed -i -e "s/\(https:\/\/img.shields.io\/badge\/version-\)[0-9.][0-9.]*\(-brightgreen.svg\)/\1$latest_version\2/" README.md
              git config --global user.name "Takafumi Umemoto"
              git config --global user.email "takafumi.umemoto@gmail.com"
              git add Dockerfile .circleci/config.yml README.md
              git commit -m "Update $latest_version [ci skip]"
              git tag $latest_version
              git push origin master
              git push origin $latest_version
            fi
  build:
    working_directory: /app
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run:
          name: Build Application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Run & Test Container
          command: |
            alias aws='docker run --rm -t $(tty &>/dev/null && echo "-i") -v "$(pwd):/project" -v "${HOME}/.aws:/root/.aws" app' 
            if [ $(aws --version | grep "${CIRCLE_TAG}") -eq 0 ]; then
              exit 1
            fi
      - run:
          name: Push Docker Image
          command: |
              docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
              docker tag app "nmemoto/aws-cli:${CIRCLE_TAG}"
              docker tag app "nmemoto/aws-cli:latest"
              docker push "nmemoto/aws-cli:${CIRCLE_TAG}"
              docker push nmemoto/aws-cli:latest
workflows:
  version: 2
  build-run-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9.]+$/
            branches:
              ignore: /.*/
  commit:
    jobs:
      - check
  regular_check:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check
